module: RestKit
author: IBM
github_url: https://github.ibm.com/MIL/RestKit

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, RestKit.xcodeproj, -target, RestKit, LIBRARY_SEARCH_PATHS=.build/debug]